CREATE TABLE book
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(200)                            NOT NULL,
    genre          VARCHAR(50)                             NOT NULL,
    price          DOUBLE PRECISION                        NOT NULL,
    currency VARCHAR(10) NOT NULL,
    language       VARCHAR(50)                             NOT NULL,
    page_number    INTEGER                                 NOT NULL,
    availability   VARCHAR(20)                             NOT NULL,
    average_rating DOUBLE PRECISION                        NOT NULL,
    author_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    book_id    BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    unit_price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ship_address VARCHAR(255)                            NOT NULL,
    order_date   date                                    NOT NULL,
    order_status VARCHAR(20)                             NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(50)                             NOT NULL,
    middle_name      VARCHAR(50),
    last_name        VARCHAR(50)                             NOT NULL,
    address          VARCHAR(255),
    telephone_number VARCHAR(20),
    birth_date       date                                    NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    book_id        BIGINT                                  NOT NULL,
    review_message VARCHAR(1000)                           NOT NULL,
    review_rating  INTEGER                                 NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status            VARCHAR(20)                             NOT NULL,
    email             VARCHAR(100)                            NOT NULL,
    registration_date date                                    NOT NULL,
    person_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE persons
    ADD CONSTRAINT uc_persons_telephone_number UNIQUE (telephone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_person UNIQUE (person_id);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES persons (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (id);