CREATE TABLE IF NOT EXISTS book
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(200)                            NOT NULL,
    genre_id       BIGINT                                  NOT NULL,
    price          DOUBLE PRECISION                        NOT NULL,
    currency       VARCHAR(10)                             NOT NULL,
    language       VARCHAR(50)                             NOT NULL,
    page_number    INTEGER                                 NOT NULL,
    availability   VARCHAR(20)                             NOT NULL,
    average_rating DOUBLE PRECISION                        NOT NULL,
    author_id      BIGINT                                  NOT NULL,
    release_date date NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    book_id    BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    unit_price DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ship_address VARCHAR(255)                            NOT NULL,
    order_date   date                                    NOT NULL,
    order_status VARCHAR(20)                             NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS persons
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(50)                             NOT NULL,
    middle_name      VARCHAR(50),
    last_name        VARCHAR(50)                             NOT NULL,
    address          VARCHAR(255),
    telephone_number VARCHAR(20),
    birth_date       date                                    NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    book_id        BIGINT                                  NOT NULL,
    review_message VARCHAR(1000)                           NOT NULL,
    review_rating  INTEGER                                 NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status            VARCHAR(20)                             NOT NULL,
    email             VARCHAR(100)                            NOT NULL,
    registration_date date                                    NOT NULL,
    person_id         BIGINT                                  NOT NULL,
    username VARCHAR(50),
    password VARCHAR(64),
    CONSTRAINT pk_users PRIMARY KEY (id)
);